# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Win64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust environment
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: cargo test
      run: |
          cargo test --release
    - name: maturin build
      run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install maturin
          maturin build --release
    - uses: actions/upload-artifact@v1
      name: upload-wheel
      with:
          name: wheel-win64
          path: target/wheels/
    - name: pip install fastrank
      run: |
          $wheel = Get-ChildItem target/wheels/fastrank-*.whl
          pip install $wheel
    - name: py-unittest
      run: |
          python -I -m unittest discover -s tests -v
